import { useEffect, useState } from 'react'
import { motion, useScroll, useSpring } from 'framer-motion'
import { ArrowDownRight, ArrowUpRight, AtSign as Linkedin, Braces, Code2 as Github, Download, Mail, MapPin, Menu, MoveUpRight, Phone, Send, Sparkles, X } from 'lucide-react'
import { projects, skills } from '../constants/portfolio'
import { ContactForm } from '../components/ContactForm'
import { CustomCursor } from '../components/CustomCursor'

const name = 'Kiruparajan Abilashan'
const initials = 'KA'
const github = 'https://github.com/abilashan-k'
const linkedin = 'https://www.linkedin.com/in/abilashan-kiruparajan'
const navItems = ['About', 'Skills', 'Work', 'Journey', 'Contact']
const reveal = { initial: { opacity: 0, y: 28 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.2 }, transition: { duration: 0.65, ease: [0.22, 1, 0.36, 1] as const } }

function SectionTitle({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) {
  return <motion.div className="section-title" {...reveal}><p className="eyebrow"><span />{eyebrow}</p><h2>{title}</h2>{copy && <p className="section-copy">{copy}</p>}</motion.div>
}

export default function Portfolio() {
  const { scrollYProgress } = useScroll()
  const scaleX = useSpring(scrollYProgress, { stiffness: 120, damping: 30 })
  const [menuOpen, setMenuOpen] = useState(false)
  const [showTop, setShowTop] = useState(false)
  useEffect(() => { const onScroll = () => setShowTop(scrollY > 700); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll) }, [])
  const scrollTo = (id: string) => { document.getElementById(id.toLowerCase())?.scrollIntoView({ behavior: 'smooth' }); setMenuOpen(false) }
  return <main><CustomCursor />
    <motion.div className="progress" style={{ scaleX }} />
    <nav className="nav"><button className="monogram" onClick={() => scrollTo('hero')} aria-label="Back to top">{initials}</button><div className={`nav-links ${menuOpen ? 'open' : ''}`}>{navItems.map(item => <button key={item} onClick={() => scrollTo(item)}>{item}</button>)}<a className="nav-cta" href="#contact">Let's talk <ArrowUpRight size={14} /></a></div><button className="menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X /> : <Menu />}</button></nav>
    <section id="hero" className="hero"><div className="hero-orb orb-one" /><div className="hero-orb orb-two" /><div className="grid-lines" /><motion.div className="hero-copy" initial={{ opacity: 0, y: 35 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8, ease: [0.22, 1, .36, 1] as const }}><p className="availability"><i />Seeking internship opportunities</p><p className="intro">Hello, I'm</p><h1>Kiruparajan<br /><em>Abilashan.</em></h1><p className="role">BIT Undergraduate <span>×</span> Aspiring Full-Stack Developer</p><p className="hero-description">I build modern, responsive web applications and continuously grow through real-world projects and thoughtful problem-solving.</p><div className="hero-actions"><a className="button primary" href="#work">Explore my work <ArrowDownRight size={18} /></a><a className="button ghost" href="/Kiruparajan-Abilashan-CV.pdf" download><Download size={17} /> Download CV</a></div></motion.div><motion.div className="hero-card" initial={{ opacity: 0, x: 40, rotate: 4 }} animate={{ opacity: 1, x: 0, rotate: 0 }} transition={{ delay: .25, duration: .8, ease: [0.22, 1, .36, 1] as const }}><div className="card-top"><span>Currently Learning</span><Sparkles size={16} /></div><div className="card-visual"><div className="visual-ring" /><div className="visual-dot" /></div><p>React, TypeScript<br /> & Full-Stack Development.</p><div className="card-bottom"><span>Open to Internships</span><ArrowDownRight size={16} /></div></motion.div><a className="scroll-note" href="#about">Discover more <span /></a></section>
    <section id="about" className="section about"><SectionTitle eyebrow="01 / About me" title="Focused on learning, building, and growing." /><div className="about-layout"><motion.div className="portrait" {...reveal} aria-label="Profile photo"><img src="/profile.jpg" alt="Kiruparajan Abilashan" className="profile-image" /><div className="portrait-tag"><span>✦</span> Batticaloa, Sri Lanka</div></motion.div><motion.div className="about-story" {...reveal}><p className="large-copy">I am a BIT undergraduate with a passion for <em>web development</em> and software engineering.</p><p>I study at the University of Moratuwa and enjoy creating modern, responsive web applications. Through real-world projects, I continually strengthen my technical skills while looking for internship opportunities where I can contribute, learn, and grow as a software developer.</p><div className="stats"><div><strong>BIT</strong><span>Undergraduate</span></div><div><strong>03</strong><span>Core projects</span></div><div><strong>∞</strong><span>Growth mindset</span></div></div></motion.div></div></section>
    <section id="skills" className="section skills"><SectionTitle eyebrow="02 / Technical skills" title="A practical toolkit for modern software." copy="A growing set of technologies I use to build responsive interfaces, desktop applications, and data-driven features." /><div className="skills-grid">{skills.map((group, index) => <motion.article className="skill-card" key={group.label} {...reveal} transition={{ ...reveal.transition, delay: index * .1 }}><span className="skill-number">0{index + 1}</span><Braces size={23} /><h3>{group.label}</h3><div className="badges">{group.items.map(item => <span key={item}>{item}</span>)}</div></motion.article>)}</div></section>
    <section id="work" className="section work"><div className="work-heading"><SectionTitle eyebrow="03 / Selected projects" title="Turning requirements into working software." /><a href={github} target="_blank" rel="noreferrer" className="text-link">Visit GitHub <MoveUpRight size={17} /></a></div><div className="projects">{projects.map((project, index) => <motion.article className={`project ${project.accent}`} key={project.title} {...reveal} transition={{ ...reveal.transition, delay: index * .08 }}><div className="project-image"><img src={project.image} alt="" loading="lazy" /><div className="image-overlay" /><a href={github} target="_blank" rel="noreferrer" aria-label={`View ${project.title} on GitHub`}><ArrowUpRight /></a></div><div className="project-info"><div><p>{project.category}</p><h3>{project.title}</h3></div><p className="project-description">{project.description}</p><div className="project-meta"><div>{project.stack.map(x => <span key={x}>{x}</span>)}</div><a href={github} target="_blank" rel="noreferrer">GitHub <Github size={15} /></a></div></div></motion.article>)}</div></section>
    <section id="journey" className="section journey"><SectionTitle eyebrow="04 / Education & direction" title="Building a foundation for a software career." /><div className="timeline"><motion.div {...reveal}><span>Current</span><div><i /><h3>Bachelor of Information Technology (BIT)</h3><p>University of Moratuwa (External)</p><small>Current undergraduate developing a strong foundation in software engineering, web development, and problem-solving.</small></div></motion.div><motion.div {...reveal}><span>Focus</span><div><i /><h3>Web development & software engineering</h3><p>Technical projects and independent learning</p><small>Continuously improving practical skills by building responsive applications and exploring modern development practices.</small></div></motion.div><motion.div {...reveal}><span>Goal</span><div><i /><h3>Software engineering internship</h3><p>Ready to contribute, learn, and grow</p><small>Seeking an internship opportunity in software engineering or web development with a collaborative team.</small></div></motion.div></div></section>
    <section id="contact" className="contact"><div className="contact-glow" /><motion.div {...reveal}><p className="eyebrow"><span />05 / Contact</p><h2>Let's build something<br /><em>valuable.</em></h2><p>I'm currently seeking internship opportunities and welcome conversations about web development and software engineering.</p><a className="email" href="mailto:abilashanki@gmail.com">abilashanki@gmail.com <ArrowUpRight /></a><div className="contact-details"><a href="tel:+94703139141"><Phone size={15} /> +94 70 313 9141</a><span><MapPin size={15} /> Batticaloa, Sri Lanka</span></div></motion.div><motion.div {...reveal}><ContactForm /></motion.div></section>
    <footer><div className="footer-top"><button className="monogram" onClick={() => scrollTo('hero')}>{initials}</button><p>Designed & built by {name}.</p><div className="socials"><a href={github} target="_blank" rel="noreferrer" aria-label="GitHub"><Github size={18} /></a><a href={linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin size={18} /></a><a href="mailto:abilashanki@gmail.com" aria-label="Email"><Mail size={18} /></a><a href="#contact" aria-label="Location"><MapPin size={18} /></a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {name}</span><span>Made in Sri Lanka <b>✦</b></span></div></footer>{showTop && <button className="to-top" onClick={() => scrollTo('hero')} aria-label="Scroll to top">↑</button>}</main>
}
